<a href="https://colab.research.google.com/github/prabuddhayogi/ai-with-python/blob/pandas/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_excel("/content/drive/MyDrive/AI-python/lecture8/new_python_dataset.xlsx")
df.head(3)

    Name  Python  Ruby  Java  Pearl
0    Ram    50.0  51.0  74.0   40.0
1   Hari    30.5  54.0  65.0   39.0
2  Shyam    49.0  45.0  40.0   55.0

In [ ]:
df.tail(3)

      Name  Python  Ruby  Java  Pearl
16  Victor    85.0  59.0  23.0   98.0
17  Rathor    19.0  63.0  54.0   65.0
18    Andy    25.0  62.1  34.0   99.0

In [ ]:
df.sample()

    Name  Python  Ruby  Java  Pearl
9  Itcha    58.0  42.0  54.6   89.0

In [ ]:
df1=df.head(3)
df1.to_csv("/content/drive/MyDrive/AI-python/lecture8/new_csv.csv")

In [ ]:
df2=pd.read_csv("/content/drive/MyDrive/AI-python/lecture8/new_csv.csv")
df2["Extra"] = df2["Python"]
df2.to_csv("/content/drive/MyDrive/AI-python/lecture8/new_csv.csv")